name: Modify and Deploy HTML

on:
  push:
    branches:
      - gh-pages  # This is the branch used for GitHub Pages

jobs:
  modify-html:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug - List Modified Files Using git diff
      run: |
        echo "Modified files in this commit:"
        git diff --name-only HEAD^ HEAD || git diff --name-only $(git hash-object -t tree /dev/null) HEAD

    - name: Modify index.html if both index.html and _markdown/index.md were modified
      run: |
        if git diff --name-only HEAD^ HEAD | grep -q '^index.html$' && git diff --name-only HEAD^ HEAD | grep -q '^_markdown/index.md$'; then
          echo "Both index.html and _markdown/index.md were modified; applying changes..."
          sed -i 's/assets.dungeonsandmarkdown.spjak.com/covalon.github.io\/covalon-guide/g' index.html  # Replace domain
          sed -i '17,48d' index.html  # Delete a style element
          sed -i '17i<link href="https://covalon.github.io/covalon-guide/styles/custom.css" rel="stylesheet" />' index.html  # Insert <link> tag at line 17
        else
          echo "index.html and _markdown/index.md were not both modified; skipping modifications."
        fi

    - name: Modify gm.html if both gm.html and _markdown/gm.md were modified
      run: |
        if git diff --name-only HEAD^ HEAD | grep -q '^gm.html$' && git diff --name-only HEAD^ HEAD | grep -q '^_markdown/gm.md$'; then
          echo "Both gm.html and _markdown/gm.md were modified; applying changes..."
          sed -i 's/assets.dungeonsandmarkdown.spjak.com/covalon.github.io\/covalon-guide/g' gm.html  # Replace domain
          sed -i '17,48d' gm.html  # Delete a style element
          sed -i '17i<link href="https://covalon.github.io/covalon-guide/styles/custom.css" rel="stylesheet" />' gm.html  # Insert <link> tag at line 17
        else
          echo "gm.html and _markdown/gm.md were not both modified; skipping modifications."
        fi

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add index.html gm.html
        git diff --quiet || git commit -m "Automated HTML updates by GitHub Actions"
        git push origin gh-pages  # Push changes back to the gh-pages branch

  deploy:
    needs: modify-html  # Ensure this runs after modifications
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      run: |
        echo "Deployment completed - GitHub Pages will automatically serve the updated content."


test